[package]
name = "dep-eval"
version = "0.1.0"
authors = ["Sebastian Puetz <sebastian.puetz@student.uni-tuebingen.de>"]
edition = "2018"

[dependencies]
clap = "2"
conllx = "0.11"
stdinout = "0.4"
ordered-float = "1"
failure = "0.1"
itertools = "0.8"